package machine;

public enum State {

    CHOOSING_ACTION,
    CHOOSING_A_VARIANT_OF_COFFEE,
    FILLING_WATER,
    FILLING_MILK,
    FILLING_COFFEE_BEANS,
    FILLING_CUPS,
    EXTRACTING_MONEY,
    SHOWING_REMAINDER
}
